### ISSUE TITLE
Strange error in Travis log

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#120]
@tdeekens  Heya!

We seem to have a new and quite strange error in the Travis log. Any idea what this could be?

```
BrowserStackTunnel: binary not present
25 10 2015 13:10:56.657:ERROR [launcher]: [TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/travis/build/cure53/DOMPurify/node_modules/karma/lib/launcher.js:94:17
    at next (/home/travis/build/cure53/DOMPurify/node_modules/karma/node_modules/batch/index.js:118:7)
    at Batch.end (/home/travis/build/cure53/DOMPurify/node_modules/karma/node_modules/batch/index.js:154:5)
    at launch (/home/travis/build/cure53/DOMPurify/node_modules/karma/lib/launcher.js:110:11)
    at invoke (/home/travis/build/cure53/DOMPurify/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/home/travis/build/cure53/DOMPurify/node_modules/karma/lib/server.js:170:24)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:104:17)
    at net.js:1171:12
    at process._tickCallback (node.js:355:11)
BrowserStackTunnel: download binary for linux-x64 ...
BrowserStackTunnel: download complete
```

https://travis-ci.org/cure53/DOMPurify#L283

**Comment by tdeekens** [comment]
...not for now - at least I've never come across that error. I'll look into it later. Maybe updating karma helps and I'd check other builds if the error previously occurred.

**Comment by cure53** [comment]
No need to hurry - thanks :) The tests are still green, just wondering what it is..

**Comment by cure53** [comment]
I'll close it for now as it doesn't seem to have any negative effects :)

**Comment by cure53** [comment]
Sorry - have to re-open. The error seems to have the builds go grey :-/

https://travis-ci.org/cure53/DOMPurify

**Comment by tdeekens** [comment]
I'll look into it later today. Might be due to an update with the tunnel module on npm. At least we had issues with it lately.

**Comment by cure53** [comment]
Thx :)

**Comment by cure53** [comment]
The builds are passing again, thanks a bunch :dancers:
