### ISSUE TITLE
Node.js instructions in README.md don't work

### ISSUE THREAD

**Issue by wirehead** [cure53/DOMPurify#151]
I was trying to get this working under node.js 4.0 and the instructions in the readme aren't working.

My test script:
```
var DOMPurify = require('dompurify');

console.log(DOMPurify.sanitize('<img src=x onerror=alert(1)//>'));
```
The output:
```
wirehead@vbox:~/src/rm3$ node blah.js 
/home/wirehead/src/rm3/blah.js:3
console.log(DOMPurify.sanitize('<img src=x onerror=alert(1)//>'));
                      ^

TypeError: DOMPurify.sanitize is not a function
    at Object.<anonymous> (/home/wirehead/src/rm3/blah.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

I think that this ends up having to do with there not being a window (unless you've loaded jsdom) and the instructions need to discuss loading jsdom, but I'm not sure.

**Comment by cure53** [comment]
Oh, good point! 

@Joris-van-der-Wel do you have a snippet at hands that works and can be used for the README?

**Comment by Joris-van-der-Wel** [comment]
There are a few flavor thats you can try:

Simplest:
```javascript
const createDOMPurify = require('dompurify');
const jsdom = require('jsdom');
const window = jsdom.jsdom().defaultView;
const DOMPurify = createDOMPurify(window);
console.log(DOMPurify.sanitize('<img src=x onerror=alert(1)//>'));
```

Extra secure:
```javascript
const createDOMPurify = require('dompurify');
const jsdom = require('jsdom');
const window = jsdom.jsdom('', {
  features: {
    FetchExternalResources: false, // disables resource loading over HTTP / filesystem
    ProcessExternalResources: false // do not execute JS within script blocks
  }
}).defaultView;
const DOMPurify = createDOMPurify(window);
console.log(DOMPurify.sanitize('<img src=x onerror=alert(1)//>'));
```
These features are strictly not necessary because internally DOMPurify creates a document without a browsing context, which means scripting should be disabled anyway. But it might mitigate a possible bug in jsdom or DOMPuiryf.

Full environment version:
```javascript
const jsdom = require('jsdom');
jsdom.env({
  html: '',
  scripts: [require.resolve('dompurify')],
  done(err, window) {
    if (err) { console.error('Error!:' , err, err.stack); }
    const DOMPurify = window.DOMPurify;
    console.log(DOMPurify.sanitize('<img src=x onerror=alert(1)//>'));
  }
});
```

**Comment by villan106** [comment]
<script>
alert(454)
</script>
