### ISSUE TITLE
Exception is thrown when parsing Invalid HTML

### ISSUE THREAD

**Issue by markb-trustifi** [cure53/DOMPurify#265]
BUG 

### Background & Context

Exception is thrown when parsing Invalid HTML

### Bug

It happens in function "Serializer.prototype._serializeAttributes", line 110.
The attribute list of the HTMLParagraphElement is NamedNodeMap and not array, thus attrs[0] is undefined when attrs['style'] returns Attr object.

#### Input

````
<p style="3D&quot;padding:0" 0="" 2px;="" font:13px="" 15px="" arial,="" helvetica,="sans-serif," roboto;="" color:#808080;="" text-decoration:none;"="">
</p>
````

#### Given output

Exception:
Cannot read property 'value' of undefined
    at Serializer._serializeAttributes (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:110:49)
    at Serializer._serializeElement (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:88:10)
    at Serializer._serializeChildNodes (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:69:22)
    at Serializer._serializeElement (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:100:14)
    at Serializer._serializeChildNodes (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:69:22)
    at Serializer._serializeElement (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:100:14)
    at Serializer._serializeChildNodes (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:69:22)
    at Serializer.serialize (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/serializer/index.js:54:10)
    at Object.exports.serialize (/Users/markba/Documents/projects/BackEnd/node_modules/parse5/lib/index.js:29:23)
    at exports.domToHtml (/Users/markba/Documents/projects/BackEnd/node_modules/jsdom/lib/jsdom/browser/domtohtml.js:16:21)
    at HTMLHtmlElementImpl.get outerHTML [as outerHTML] (/Users/markba/Documents/projects/BackEnd/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:145:12)
    at HTMLHtmlElement.get [as outerHTML] (/Users/markba/Documents/projects/BackEnd/node_modules/jsdom/lib/jsdom/living/generated/Element.js:828:22)
    at Function.DOMPurify.sanitize (/Users/markba/Documents/projects/BackEnd/node_modules/dompurify/dist/purify.cjs.js:860:33)

#### Expected output

`<p></p>`

**Comment by cure53** [comment]
Hmmm, I cannot seem to reproduce. Tested on Firefox & Chrome. 
Did you try the latest release or the latest version in master?

When testing, I get `<p style="3D&quot;padding:0"></p>` as expected.

**Comment by cure53** [comment]
@markb-trustifi We investigated and discovered that it's not our bug, we cannot fix it :D

The problem is caused by older versions of _jsdom_. We used the latest version and the issue disappears. I think it might be best to either upgrade your version of _jsdom_ or report the issue to them. There is 100% nothing we can do, sorry.
