### ISSUE TITLE
Odd error with jsdom 12.2.0 and certain stylesheet-related elements

### ISSUE THREAD

**Issue by sbassett29** [cure53/DOMPurify#311]
### Bug

While testing DOMPurify 1.0.8 with JSDOM 12.2.0 under Node 10.11.0, I noticed some odd errors with certain stylesheet-related elements.  Testing the same elements within JSDOM (e.g. `const { document } = (new JSDOM('<link rel="stylesheet" href="https://leaking.via/link-stylesheet" />')).window;`) seems to work fine.

#### Input

```
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');
const window = (new JSDOM('')).window;
const DOMPurify = createDOMPurify(window);

const clean1 = DOMPurify.sanitize( '<link rel="stylesheet" href="https://leaking.via/link-stylesheet" />' );
const clean2 = DOMPurify.sanitize('<link rel="alternate stylesheet" href="https://leaking.via/link-alternate-stylesheet" />');
const clean3 = DOMPurify.sanitize("<style>@import 'https://leaking.via/css-import-string';</style>");
```

#### Given output

```
/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:16
    const request = this._resourceLoader.fetch(url, {
                                         ^

TypeError: Cannot read property 'fetch' of null
    at PerDocumentResourceLoader.fetch (/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:16:42)
    at fetchStylesheetInternal (/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:77:18)
    at scanForImportRules (/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:109:9)
    at exports.createStylesheet (/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:43:3)
    at HTMLStyleElementImpl._updateAStyleBlock (/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
    at HTMLStyleElementImpl._attach (/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:19:12)
    at HTMLHeadElementImpl._attach (/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:303:15)
    at HTMLHeadElementImpl._attach (/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:87:11)
    at HTMLHtmlElementImpl.insertBefore (/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:243:18)
    at HTMLBodyElementImpl.set outerHTML [as outerHTML] (/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:173:14)
```

#### Expected output

Not an error.

**Comment by cure53** [comment]
Hmmm, sure this is our bug? It looks a bit like this issue:

https://github.com/jsdom/jsdom/issues/2374

**Comment by sbassett29** [comment]
Ah, yes, that seems to be the issue.  I hadn't tested the same way as the reporters within the JSDOM issue had, and therefore didn't think JSDOM by itself was the issue.  I'd guess this could be closed now - thanks for investigating.

**Comment by 7twin** [comment]
@sbassett29 if you haven't found the fix yourself yet, then you can merge in the PR locally and point dompurify to use it: https://github.com/jsdom/jsdom/pull/2510
