### ISSUE TITLE
Build fails again

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#333]
The build fails again for no apparent reason, error being:

```
> dompurify@1.0.10 lint /home/travis/build/cure53/DOMPurify
> xo src/*.js
TypeError: (0 , _ignore.getFileExtensions) is not a function
Occurred while linting /home/travis/build/cure53/DOMPurify/src/purify.js:1
    at checkSourceValue (/home/travis/build/cure53/DOMPurify/node_modules/eslint-plugin-import/lib/rules/no-useless-path-segments.js:103:60)
    at checkSourceValue (/home/travis/build/cure53/DOMPurify/node_modules/eslint-module-utils/moduleVisitor.js:29:5)
    at checkSource (/home/travis/build/cure53/DOMPurify/node_modules/eslint-module-utils/moduleVisitor.js:34:5)
    at listeners.(anonymous function).forEach.listener (/home/travis/build/cure53/DOMPurify/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/travis/build/cure53/DOMPurify/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/travis/build/cure53/DOMPurify/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/travis/build/cure53/DOMPurify/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/home/travis/build/cure53/DOMPurify/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/home/travis/build/cure53/DOMPurify/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
npm ERR! code ELIFECYCLE
```

https://travis-ci.org/cure53/DOMPurify/jobs/519612740

@tdeekens any idea what caused this? I tried ti find an explanation but failed so far.

**Comment by cure53** [comment]
Locally it works all fine btw.

**Comment by cure53** [comment]
Okay, now I can reproduce locally as well. As a temporary fix, I disabled linting for the builds. Any idea what happened to the `xo src/*js` call so the linter breaks? @tdeekens

**Comment by cure53** [comment]
It appears to be these lines in `purify,js` that cause the linter to break:

```
import * as TAGS from './tags';
import * as ATTRS from './attrs';
import { addToSet, clone } from './utils';
import * as EXPRESSIONS from './regexp';
```

**Comment by tdeekens** [comment]
No idea, didn‘t happen to me before. Can try to investigate a bit later.

**Comment by cure53** [comment]
> No idea, didn‘t happen to me before. Can try to investigate a bit later.

Same here, I managed to narrow it down to the imports in `purify.js`, now clueless how to proceed :D

**Comment by cure53** [comment]
This appears to do the trick: https://github.com/cure53/DOMPurify/commit/2a6a5abdd4ea94fa229850b7df283e04c5da95f3

**Comment by tdeekens** [comment]
Maybe it's also worth changing the imports. I was also thinking about moving the project to CircleCI after the recent noise about TravisCI. Other projects also build faster there and the configuration options are far more flexible.
