### ISSUE TITLE
NoModificationAllowedError

### ISSUE THREAD

**Issue by charlag** [cure53/DOMPurify#370]
We observe stacktraces like
```
Error: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
at _forceRemove (https://mail.tutanota.com/theme.js:1:26863)
at _sanitizeAttributes (https://mail.tutanota.com/theme.js:1:32642)
at Function.sanitize (https://mail.tutanota.com/theme.js:1:35586)
at HtmlSanitizer.value (https://mail.tutanota.com/main.js:1:1487658)
at https://mail.tutanota.com/main.js:1:310896
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
at F._fulfill (https://mail.tutanota.com/libs.js:26:48411)
at F._resolveCallback (https://mail.tutanota.com/libs.js:26:45290)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46696)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromise0 (https://mail.tutanota.com/libs.js:26:48041)
at F._settlePromises (https://mail.tutanota.com/libs.js:26:49393)
```

see https://github.com/tutao/tutanota/issues/1539

Mostly Chrome 69-77 but also Safari on iOS

**Comment by cure53** [comment]
Interesting, so we know the HTML where this error is coming from?

**Comment by cure53** [comment]
So, it should come from this snippet as this is the only call of `_forceRemove` from inside `_sanitizeAttributes` - and indeed that was added to mitigate an mXSS.

I think we should be safe with a try/catch here - but it would be very interesting to learn what causes it.

**Comment by cure53** [comment]
We could probably also go with a change like this - but need proper testing for that.

```javascript
      /* Check for possible Chrome mXSS, least aggressively */
      if (
        (ALLOWED_TAGS.svg && !FORBID_TAGS.svg) ||
        (ALLOWED_TAGS.math && !FORBID_TAGS.math)
      ) {
        if (removeSVGAttr && /<\//.test(value)) {
          _removeAttribute(name, currentNode); // only remove attribute, not whole element
        }
      }
```

**Comment by charlag** [comment]
Yes, that's the place
We couldn't reproduce it ourselves, it's just a bug report, I may try to ask users to send us such content.
I suspect that may be when there are multiple elements at the top level (we sanitize emails and we take only inner HTML part, without body and everything so there may be multiple children at the top level). Then they will probably hve no parent element so no outerHTML. That's only a guess though.

**Comment by cure53** [comment]
We just pushed a change - the issue _should_ be fixed on master.

**Comment by cure53** [comment]
Okay, we have a new version on master that, as we believe, does not need the old mXSS checks any longer and the new ones are _much_ less invasive. I believe the error should be gone.
