### ISSUE TITLE
Creating command-line executable of DOMPurify

### ISSUE THREAD

**Issue by sdbbs** [cure53/DOMPurify#531]
> This issue documents one way how to make DOMPurify into a standalone command line executable - so, it is not a bug.

### Background & Context

I really wanted to try and use DOMPurify from the command line, and so found https://dev.to/jochemstoel/bundle-your-node-app-to-a-single-executable-for-windows-linux-and-osx-2c89 and tried to follow it. I'm not really a JS/node dev, so this is only a start.

Prerequisites:

```none
$ npm install pkg
npm WARN peerDependencies The peer dependency node-notifier@>=6.0.0 included from pkg will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN engine chalk@3.0.0: wanted: {"node":">=8"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN engine into-stream@5.1.1: wanted: {"node":">=8"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN engine prebuild-install@6.0.1: wanted: {"node":">=6"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN engine @babel/parser@7.13.12: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN engine globby@11.0.3: wanted: {"node":">=10"} (current: {"node":"4.8.4","npm":"2.15.11"})
....
pkg@4.5.1 node_modules/pkg
├── progress@2.0.3
├── minimist@1.2.5
├── @babel/parser@7.13.12
...

$ npm install jsdom
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> pre-commit@1.2.2 install /home/adminec/DOMPurify/node_modules/pre-commit
> node install.js
...
+ jsdom@16.5.3
added 1266 packages from 1136 contributors and audited 1275 packages in 41.125s

80 packages are looking for funding
  run `npm fund` for details

found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

First:

```bash
git clone https://github.com/cure53/DOMPurify.git
```

Then, in the DOMPurify folder:

1. Create `main.js`:

```js
/* You might want to check first if the file exists and stuff but this is an example. */
const fs = require('fs')
const createDOMPurify = require('../DOMPurify'); // works, to refer to the library in this repo!
const { JSDOM } = require('jsdom');
module.exports = function(filePath, options) {
  let dirtydata = fs.readFileSync(filePath).toString() /* open the file as string */
  const window = new JSDOM('').window;
  const DOMPurify = createDOMPurify(window);
  const clean = DOMPurify.sanitize(dirtydata, options);
  return clean;
}
```

2. Create `bin.js`:

```js
const dompurify = require('./main.js') /* in the current working directory */
let theFile = process.argv[2] /* what the user enters as first argument */
let theOptions = process.argv[3] /* what the user enters as second argument */

console.log(
  dompurify(theFile, theOptions)
)
```

3. Change `package.json` according to this diff (except for the "jsdom" line, that change is automatic):

```none
$ git diff package.json
diff --git a/package.json b/package.json
index 5dfb927..fc78416 100644
--- a/package.json
+++ b/package.json
@@ -19,6 +19,7 @@
     "test": "cross-env NODE_ENV=test BABEL_ENV=rollup npm run lint &&  npm run test:jsdom && npm run test:karma -- --browsers Chrome"
   },
   "main": "dist/purify.cjs.js",
+  "bin": "bin.js",
   "module": "dist/purify.es.js",
   "browser": "dist/purify.js",
   "files": [
@@ -71,7 +72,7 @@
     "eslint-plugin-prettier": "^3.1.3",
     "he": "^1.2.0",
     "jquery": "^3.5.0",
-    "jsdom": "16.x.x",
+    "jsdom": "^16.5.3",
     "karma": "^5.1.0",
     "karma-browserstack-launcher": "^1.5.1",
     "karma-chrome-launcher": "^2.2.0",
@@ -133,5 +134,7 @@
     "url": "https://github.com/cure53/DOMPurify/issues"
   },
   "homepage": "https://github.com/cure53/DOMPurify",
-  "dependencies": {}
+  "dependencies": {
+    "dompurify": "file:./"
+  }
 }
```

4. Run `pkg` - note that, if it was not installed with the `-g` switch of `npm`, then it will end up in `~/node_modules/.bin/pkg`:

```none
$ ~/node_modules/.bin/pkg .
> pkg@4.5.1
> Targets not specified. Assuming:
  node14-linux-x64, node14-macos-x64, node14-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-linux-x64    [====================] 100%
  fetched-v14.4.0-macos-x64    [====================] 100%
  fetched-v14.4.0-win-x64      [====================] 100%
> Warning Cannot find module 'dompurify' from '/home/adminec/DOMPurify'
  %1: /home/adminec/DOMPurify/bin.js
> Warning Cannot find module 'dompurify/package.json' from '/home/adminec/DOMPurify'
  %1: /home/adminec/DOMPurify/bin.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/DOMPurify/dist/purify.es.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/DOMPurify/dist/purify.es.js
> Warning Failed to make bytecode node14-x64 for file C:\snapshot\DOMPurify\dist\purify.es.js
```

In spite of the warnings, it generates files:

```
$ ls -la dompurify-*
-rwxrwxr-x 1 user user 90863782 Apr 13 17:31 dompurify-linux
-rwxrwxr-x 1 user user 91109158 Apr 13 17:27 dompurify-macos
-rw-rw-r-- 1 user user 92489723 Apr 13 17:31 dompurify-win.exe
```

... and they seem to work; note that if you call the command without any command line arguments, you get this:

```none
$ ./dompurify-linux
internal/fs/utils.js:568
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:453:10)
    at Object.openSync (pkg/prelude/bootstrap.js:505:32)
    at Object.readFileSync (fs.js:364:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:758:36)
    at /snapshot/DOMPurify/main.js:8:22
    at Object.<anonymous> (/snapshot/DOMPurify/bin.js:6:3)
    at Module._compile (pkg/prelude/bootstrap.js:1433:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

... however, with at least a file argument, it seems to work:

```none
$ ./dompurify-linux ./node_modules/psl/browserstack-logo.svg
<svg xml:space="preserve" style="enable-background:new 0 0 490.1 105.6;" viewBox="0 0 490.1 105.6" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
<style type="text/css">
        .st0{fill:#F4B960;}
        .st1{fill:#E66F32;}
        .st2{fill:#E43C41;}
        .st3{fill:#BDD041;}
...
        c-0.1,0.1-0.2,0.1-0.3,0.1H482.8L482.8,73.3z" class="st11"></path>
</svg>
```

Nice, I have a command line executable now!

**Comment by cure53** [comment]
This is super-cool :D

**Comment by sdbbs** [comment]
Thanks @cure53 :

> Can I tweet this or will you make changes? The ticket was closed already, hence asking.

I wasn't intending to make changes, but I realized there was an error (forgot to JSON.parse the option string), which I hopefully just now... So, now I should not be making any more changes - so it is fine to tweet! :)

**Comment by sdbbs** [comment]
EDIT: btw, I closed the bug because I did not know whether development was keen on having a command line tool as well, and it ended up being a method that worked (I just wanted to report, did not really need assistance) - but if there is a chance command line builds might be available in the future, feel free to reuse/reopen this bug,

**Comment by cure53** [comment]
Cool, thanks!
